title: Your Site Title
description: Your site description
baseurl: ""
url: "https://moutaouakkil.github.io"

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/